### ISSUE TITLE
I didn't any change, but I got the error. 

### ISSUE THREAD

**Issue by ajnudnyy** [andyet/simplewebrtc-talky-sample-app#1]
Failed to compile
D:/Project/crm/talky/src/components/ChatToggle.tsx
TypeScript error: Argument of type '(props: ContainerProps) => { position: string; bottom: number; right: number; width: string; textAlign: string; zIndex: number; fontSize: string; border: string; background: string; padding: string; '&:focus': { ...; }; '& svg': { ...; }; }' is not assignable to parameter of type 'TemplateStringsArray'.
  Type '(props: ContainerProps) => { position: string; bottom: number; right: number; width: string; textAlign: string; zIndex: number; fontSize: string; border: string; background: string; padding: string; '&:focus': { ...; }; '& svg': { ...; }; }' is missing the following properties from type 'TemplateStringsArray': raw, concat, join, slice, and 16 more.  TS2345

    14 | }
    15 | 
  > 16 | const Container = styled.button((props: ContainerProps) => ({
       |                                 ^
    17 |   position: 'absolute',
    18 |   bottom: 0,
    19 |   right: 0,****

**Comment by bzemel** [comment]
This issue can be fixed with a fresh clone, install, and start.
