### ISSUE TITLE
The sample cannot start running due to script issue, need help

### ISSUE THREAD

**Issue by jianglong98** [andyet/simplewebrtc-talky-sample-app#2]
lab@srbhwebrtc:~/webrtc/simplewebrtc-talky-sample-app$ sudo npm start

> simplewebrtc-demo-talky@1.0.0 start /home/lab/webrtc/simplewebrtc-talky-sample-app
> react-scripts start

/home/lab/webrtc/simplewebrtc-talky-sample-app/node_modules/react-dev-utils/WebpackDevServerUtils.js:166
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lab/webrtc/simplewebrtc-talky-sample-app/node_modules/react-scripts/scripts/start.js:45:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplewebrtc-demo-talky@1.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplewebrtc-demo-talky@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-01T16_26_37_243Z-debug.log

**Comment by jianglong98** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v6.14.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle simplewebrtc-demo-talky@1.0.0~prestart: simplewebrtc-demo-talky@1.0.0
6 info lifecycle simplewebrtc-demo-talky@1.0.0~start: simplewebrtc-demo-talky@1.0.0
7 verbose lifecycle simplewebrtc-demo-talky@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle simplewebrtc-demo-talky@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lab/webrtc/simplewebrtc-talky-sample-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle simplewebrtc-demo-talky@1.0.0~start: CWD: /home/lab/webrtc/simplewebrtc-talky-sample-app
10 silly lifecycle simplewebrtc-demo-talky@1.0.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle simplewebrtc-demo-talky@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle simplewebrtc-demo-talky@1.0.0~start: Failed to exec start script
13 verbose stack Error: simplewebrtc-demo-talky@1.0.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid simplewebrtc-demo-talky@1.0.0
15 verbose cwd /home/lab/webrtc/simplewebrtc-talky-sample-app
16 verbose Linux 4.9.0-6-686-pae
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v6.14.4
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error simplewebrtc-demo-talky@1.0.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the simplewebrtc-demo-talky@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bzemel** [comment]
This issue can be fixed with a fresh clone, install, and start.

**Comment by bzemel** [comment]
You'll also want to upgrade to Node 8+ (10 would be best).

**Comment by jianglong98** [comment]
I updated the API key in index.tsx, but get the notice when login http:/localhost:3000
Edit src/index.tsx to set your API key.
Visit simplewebrtc.com to sign up and get an API key.

Currently I have API Key as trial, not pricing account. But it should allow me to try several times to see if it is working properly, then make decision to buy, right?

**Comment by jianglong98** [comment]
Subscription Info
You are currently subscribed to our free starter plan
