### ISSUE TITLE
API Key in trail account

### ISSUE THREAD

**Issue by jianglong98** [andyet/simplewebrtc-talky-sample-app#3]
I updated the API key in index.tsx, but get the notice when login http:/localhost:3000
Edit src/index.tsx to set your API key.
Visit simplewebrtc.com to sign up and get an API key.

Currently I have API Key as trial, not pricing account. But it should allow me to try several times to see if it is working properly, then make decision to buy, right?

**Comment by bzemel** [comment]
Did you replace 'YOUR_API_KEY' on both lines 22 and 41 of index.tsx? That could potentially cause this issue. You should only replace the value on line 22, and leave 41 as it is.

**Comment by jianglong98** [comment]
I did replace on both line#22/41. But I am wondering if the code syntax(===) is wrong below:
JavaScript has both strict and type–converting comparisons. A strict comparison (e.g., ===) is only true if the operands are of the same type and the contents match. 
In my understanding, if the API Key is not matching, the reminding notification text should not display on web, right? Thus why the code below keep asking set API Key even the API Key is strictly matching!
if (API_KEY === 'xxxxxxxxx') {
  ReactDOM.render(
    <div>
      <p>Edit src/index.tsx to set your API key.</p>
      <p>Visit <a href="https://simplewebrtc.com">simplewebrtc.com</a> to sign up and get an API key.</p>
    </div>,
    document.getElementById('root')
  );

**Comment by bzemel** [comment]
The code block beginning on line 41 is only there to remind you to get the key from us, which is why it should remain unchanged (i.e. checking that the constant on line 22 has changed). If you switch the API key on line 41 back to 'YOUR_API_KEY', you should not continue to encounter this issue.

**Comment by bzemel** [comment]
We've updated the sample app to make this more clear. I'll close this issue, but let me know if you have any additional problems with the sample app.
